-- CREATE SCHEMA SHOP;

-- SET SCHEMA SHOP;

CREATE TABLE IF NOT EXISTS WATCH_CATALOG
(
    ITEM_ID SERIAL PRIMARY KEY,
    WATCH_ID VARCHAR,
    WATCH_NAME VARCHAR,
    WATCH_DESCRIPTION VARCHAR,
    UNIT_PRICE INTEGER
);

CREATE TABLE IF NOT EXISTS WATCH_CATALOG_DISCOUNT
(
    DISCOUNT_ID          SERIAL PRIMARY KEY,
    ITEM_ID              INT references WATCH_CATALOG (ITEM_ID),
    DISCOUNT_DESCRIPTION VARCHAR,
    DISCOUNT_ITEM_COUNT  INTEGER,
    DISCOUNT_PRICE       INTEGER,
    IS_ACTIVE            BOOLEAN
);

